version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: mei-organizer-backend
    volumes:
      - .:/var/www/html
      - ./docker/backend/php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
    networks:
      - mei-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: mei-organizer-frontend
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    ports:
      - "5173:5173"
    networks:
      - mei-network

  nginx:
    image: nginx:alpine
    container_name: mei-organizer-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    networks:
      - mei-network

  mysql:
    image: mysql:8.0
    container_name: mei-organizer-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mei-network

networks:
  mei-network:
    driver: bridge

volumes:
  mysql-data: 