
CREATE TABLE vibbrance.PRODUTO (
   ID INT AUTO_INCREMENT PRIMARY KEY,
   NOME VARCHAR(200) NOT NULL,
   DESCRICAO VARCHAR(500),
   PRECO DOUBLE,
   DISP_TROCA TINYINT(1),  
   CONTATO VARCHAR(15),
   ID_CATEGORIA INT,
   STATUS_VENDA VARCHAR(20),
   FOTO BLOB,
   ATIVO TINYINT(1)      
);



CREATE TABLE CATEGORIAS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	DESCRICAO VARCHAR(500)
); 

ALTER TABLE PRODUTO
ADD CONSTRAINT fk_categoria_produto
 FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID);
 
  INSERT INTO CATEGORIAS (DESCRICAO)
 VALUES ('ELETRONICOS');
 
 INSERT INTO CATEGORIAS (DESCRICAO)
 VALUES ('AUDIO E IMAGEM');
 
 INSERT INTO CATEGORIAS (DESCRICAO)
 VALUES ('PRODUTOS DIVERSOS');
 
 
 INSERT INTO PRODUTO (NOME, DESCRICAO, ID_CATEGORIA, PRECO, ATIVO, STATUS_VENDA, FOTO, DISP_TROCA, CONTATO)
 VALUES
  ('PLAYSTATION', 'PS4 FAT ACOMPANHANDO DOIS JOGOS. SEMINOVO E COM NOTA FICAL',  1, 2550.60 , 1, 'À VENDA', NULL, 1,  '85986747311' );
   
 INSERT INTO PRODUTO (NOME, DESCRICAO, ID_CATEGORIA, PRECO, ATIVO, STATUS_VENDA, FOTO, DISP_TROCA, CONTATO)
 VALUES
 ('CAIXA DE SOM', 'CAIXA DE SOM JBL SEMINOVA',  1, 300.00 , 1, 'À VENDA', NULL, 1,  '85986747311' );
  
   
 INSERT INTO PRODUTO (NOME, DESCRICAO, ID_CATEGORIA, PRECO, ATIVO, STATUS_VENDA, FOTO, DISP_TROCA, CONTATO)
 VALUES
  ('TÊNIS ADDIDAS PREDATOR', 'PRODUTO NOVO COM NOTA FISCAL',  1, 300.00 , 1, 'À VENDA', NULL, 1,  '85986747311' );
  
   
 INSERT INTO PRODUTO (NOME, DESCRICAO, ID_CATEGORIA, PRECO, ATIVO, STATUS_VENDA, FOTO, DISP_TROCA, CONTATO)
 VALUES
 ('CADEIRA GAMER', 'CADEIRA GAMER SEMINOVA',  1, 600.00 , 1, 'À VENDA', NULL, 1,  '85986747311' );
